service: winston-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  environment:
    STAGE: ${opt:stage, 'dev'}

plugins:
  - serverless-plugin-typescript

functions:
  test:
    handler: src/handler.handler
